title: r0nn1nx0
description: On this website I put together tutorials and documentation on HTB exercises, I am not a professional, I do this to improve my learning and help people like me, any constructive criticism is welcome =)

  En esta pagina web colagare tutoriales y documentación sobre ejercicios de HTB, no soy ningun profesional esto lo hago para mejorar mi aprendizaje y ayudar a gente novata como yo, cualquier critica constructiva es bienvenida =)
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
